### ISSUE TITLE
AWS Cloud Billing Issue

### ISSUE THREAD

**Issue by Burak-Cosar** [Burak-Cosar/SWE573-Cosar#26]
I deployed the MVP on AWS, using an EC2 to deploy the container image of my Django application connected to a PostgreSQL Database instance on RDS.

Likely due to the usage of public IPv4 between the containerized application and RDS, I am hourly getting charged by AWS VPC.

- [x] Containerize the database 
- [x] Deploy everything on EC2 together.

**Comment by yashdeored** [comment]
Well if you are using elastic network interface which stands for ENI for a consistent public IPv4 it costs money and also any IPv4 has started to cost money as there are shortage of those so I would recommend you to use IPv6 address and connect it with Egress-only internet gateways. It will lower your cost more ! Also use Aurora Postgres SQL serverless so its easy to manage but you can change the way you like. Feel free to text me if you need any help

**Comment by Burak-Cosar** [comment]
App redeployed with dockerized DB.
